version: "3"
services:
  app:
    build:
      context: .
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev  # Adjust command as needed for your application

  test:
    build:
      context: .
    env_file:
      - ./.env.test  # Use a different env file for testing
    depends_on:
      - mongodb_test
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run test:e2e  # Adjust command to run your E2E test suite

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongodb_test:
    image: mongo:latest
    container_name: mongodb_test
    ports:
      - "27018:27017"  # Use a different port to avoid conflicts
    volumes:
      - mongodb_test_data:/data/db

volumes:
  mongodb_data:
  mongodb_test_data:
